// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/csr": {
    params: {};
  };
  "/ssr": {
    params: {};
  };
  "/ssg": {
    params: {};
  };
  "/cached": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/csr" | "/ssr" | "/ssg" | "/cached" | "/*";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/csr.tsx": {
    id: "routes/csr";
    page: "/csr";
  };
  "routes/ssr.tsx": {
    id: "routes/ssr";
    page: "/ssr";
  };
  "routes/ssg.tsx": {
    id: "routes/ssg";
    page: "/ssg";
  };
  "routes/cached.tsx": {
    id: "routes/cached";
    page: "/cached";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};